# Generated by Django 5.1 on 2024-09-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_producto', models.CharField(max_length=50)),
                ('Codigo_producto', models.CharField(max_length=50)),
                ('Categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='ciudad_lugar',
        ),
        migrations.AddField(
            model_name='ciudad',
            name='codigo_postal',
            field=models.CharField(default='0000', max_length=50),
            preserve_default=False,
        ),
    ]
